"use client";
import { useEffect,useState } from 'react';
import { firmDirectory,firmRequest,type FirmDirectory,type OrganizationPerson } from '../../lib/beta-cloud';
import { roles,type Role } from '../../lib/beta';
const disclosure='Vid godkännande kan båda företagen se varandras anställda, namn, telefonnummer och e-postadresser. Arbetsordrar delas inte.';
export default function CompanySharing({workspace,revision,demo,onMessage,onChanged}:{workspace:string;revision:number;demo:boolean;onMessage:(text:string)=>void;onChanged:()=>Promise<void>}){
 const [data,setData]=useState<FirmDirectory|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[search,setSearch]=useState(''),[person,setPerson]=useState<OrganizationPerson|null>(null),[selected,setSelected]=useState('');
 useEffect(()=>{let cancelled=false;setData(null);setPerson(null);setError('');if(demo){setData({firms:[],requests:[]});return;}firmDirectory(workspace).then(value=>{if(!cancelled)setData(value);}).catch(e=>{if(!cancelled)setError(e.message);});return()=>{cancelled=true;};},[workspace,revision,demo]);
 async function send(target:string,action:string){if(busy)return;setBusy(true);setError('');try{setData(await firmRequest(workspace,target,action));setPerson(null);await onChanged();onMessage(action==='request'?'Förfrågan skickad. '+disclosure:action==='accept'?'Förfrågan godkänd. '+disclosure:'Förfrågan uppdaterad.');}catch(e){setError(e instanceof Error?e.message:'Förfrågan kunde inte sparas.');}finally{setBusy(false);}}
 const active=data?.firms.find(f=>f.id===selected);
 return <section className="panel content-panel firm-sharing"><h2>Företag i Brief</h2><p className="muted">{disclosure}</p>{error&&<p className="notice" role="alert">{error}</p>}{!data&&!error&&<p role="status">Hämtar företag…</p>}
 <label>Sök registrerat företag<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Företagsnamn" /></label>
 <div className="firm-list">{data?.firms.filter(f=>f.name.toLocaleLowerCase('sv').includes(search.toLocaleLowerCase('sv'))).map(f=>{const pending=data.requests.some(r=>r.state==='pending'&&[r.sender,r.recipient].includes(f.id));return <div key={f.id} className="person-row"><strong>{f.name}</strong>{f.shared?<button onClick={()=>{setSelected(f.id);setPerson(null);}}>Visa organisation</button>:pending?<span className="muted">Förfrågan väntar</span>:<button disabled={busy} onClick={()=>{if(confirm(`Skicka förfrågan till ${f.name}?\n\n${disclosure}`))void send(f.id,'request');}}>Begär kontaktåtkomst</button>}</div>;})}</div>
 {active?.shared&&<section className="organization-chart"><h3>{active.name}</h3>{['Beställare / Platschef','Platschef / Arbetsledare','Arbetare'].map((name,index)=><div className="organization-level" key={name}><h4>{name}</h4><div className="organization-people">{active.people.filter(p=>(p.role==='worker'?2:p.role==='supervisor'||(p.role==='site_manager'&&p.organizationLevel!=='client')?1:0)===index).map(p=><button className="organization-person" key={p.id} onClick={()=>setPerson(p)}><strong>{p.name}</strong><small>{roles[p.role as Role]||'Beställare'}</small></button>)}</div></div>)}</section>}
 {person&&<div className="contact-card" role="region" aria-label={'Kontaktuppgifter för '+person.name}><button onClick={()=>setPerson(null)} aria-label="Stäng kontaktkort">×</button><h3>{person.name}</h3><p>{roles[person.role as Role]||'Beställare'} · {person.employer}</p><p>{person.phone?<a href={'tel:'+person.phone}>{person.phone}</a>:'Telefon ej angivet'}</p><p>{person.email?<a href={'mailto:'+person.email}>{person.email}</a>:'E-post ej angiven'}</p></div>}
 <h3>Företagsförfrågningar</h3>{data?.requests.map(r=><div className="firm-request" key={r.id}><strong>{r.senderName} → {r.recipientName}</strong><p>{roles[r.role as Role]} · {{pending:'Väntar på svar',accepted:'Kontaktåtkomst godkänd',declined:'Avböjd',revoked:'Återkallad'}[r.state]}</p>{r.state==='pending'&&<p className="muted">{disclosure}</p>}{r.state==='pending'&&r.canRespond&&<div className="actions"><button className="primary" disabled={busy} onClick={()=>{if(confirm('Godkänn ömsesidig kontaktåtkomst?\n\n'+disclosure))void send(r.id,'accept');}}>Godkänn</button><button disabled={busy} onClick={()=>void send(r.id,'decline')}>Avböj</button></div>}{r.state==='pending'&&r.incoming&&!r.canRespond&&<p className="muted">En {roles[r.role as Role]} i ditt företag behöver svara.</p>}{(r.state==='pending'&&!r.incoming||r.state==='accepted')&&<button disabled={busy} onClick={()=>void send(r.id,'revoke')}>{r.state==='accepted'?'Avsluta kontaktåtkomst':'Återkalla förfrågan'}</button>}</div>)}{data&&!data.requests.length&&<p className="muted">Inga företagsförfrågningar ännu.</p>}
 </section>;
}
