const {chromium}=require('playwright-core'),assert=require('node:assert/strict'),{spawn}=require('node:child_process');
const server=spawn(process.execPath,['node_modules/next/dist/bin/next','start','--hostname','127.0.0.1','--port','3010'],{stdio:['ignore','pipe','pipe']});
(async()=>{
 await new Promise((resolve,reject)=>{server.stdout.on('data',d=>{if(d.toString().includes('Ready'))resolve();});server.once('error',reject);server.once('exit',code=>reject(Error('Server exited '+code)));});
 const browser=await chromium.launch({executablePath:process.env.BRIEF_CHROMIUM_EXECUTABLE,args:['--no-sandbox','--disable-dev-shm-usage'],headless:true});
 try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:3010');await page.getByText('Logga in till din arbetsyta.',{exact:true}).waitFor();
 assert.equal(await page.getByRole('button',{name:/Registrera|Skapa konto/}).count(),0);
 await page.getByRole('button',{name:'Byt till mörkt tema',exact:true}).click();assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');assert.equal(await page.locator('.theme-picker select').count(),0);
 await page.getByRole('button',{name:'Öppna demonstration',exact:true}).click();await page.getByRole('heading',{name:'Översikt',exact:true}).waitFor();
 await page.getByRole('button',{name:'Öppna kontomeny'}).click();assert.equal(await page.locator('.account-dropdown input[type="search"]').count(),0);await page.getByRole('button',{name:/Mina kollegor/}).click();await page.getByRole('heading',{name:'Mina kollegor',exact:true}).waitFor();
 await page.getByRole('button',{name:'+ Lägg till konto'}).click();const dialog=page.getByRole('dialog');await dialog.getByRole('button',{name:'Spara',exact:true}).click();assert(await dialog.getByRole('alert').textContent().then(t=>t.includes('Förnamn')&&t.includes('Tilldelat lösenord')));assert.equal(await dialog.getByLabel('Företag', {exact:false}).inputValue(),'Brief Bygg');assert.equal(await dialog.getByLabel('Företag',{exact:false}).getAttribute('readonly'),'');assert.equal(await dialog.getByLabel('Tilldelat lösenord',{exact:false}).getAttribute('minlength'),'8');await dialog.getByRole('button',{name:'Avbryt'}).click();
 await page.getByRole('button',{name:'Öppna kontomeny'}).click();await page.getByRole('button',{name:/Min profil/}).click();await page.getByRole('heading',{name:'Ändra din profil',exact:true}).waitFor();await page.getByRole('button',{name:'Byt lösenord',exact:true}).click();await page.getByLabel('Nytt lösenord',{exact:true}).fill('MittNya123');await page.getByLabel('Bekräfta lösenord',{exact:true}).fill('InteSamma123');await page.getByRole('button',{name:'Spara lösenord'}).click();await page.getByText('Bekräfta lösenord: lösenorden måste vara lika.',{exact:true}).first().waitFor();await page.getByLabel('Bekräfta lösenord',{exact:true}).fill('MittNya123');await page.getByRole('button',{name:'Spara lösenord'}).click();await page.getByRole('heading',{name:'Översikt',exact:true}).waitFor();
 for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:900});const button=page.getByRole('button',{name:'Ny arbetsorder',exact:true});assert(await button.isVisible());assert.equal(await button.innerText(),'Ny arbetsorder');const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);if(overflow)console.log(await page.evaluate(()=>({doc:document.documentElement.scrollWidth,inner:innerWidth,elements:[...document.querySelectorAll('body *')].filter(e=>e.scrollWidth>e.clientWidth+1&&e.clientWidth>0).slice(0,15).map(e=>({cls:e.className,tag:e.tagName,scroll:e.scrollWidth,client:e.clientWidth,overflow:getComputedStyle(e).overflowX}))})));if(overflow)console.log(await page.evaluate(()=>[...document.querySelectorAll('body *')].filter(e=>e.getBoundingClientRect().right>innerWidth+1).slice(0,20).map(e=>({tag:e.tagName,cls:e.className,text:e.textContent.slice(0,80),right:e.getBoundingClientRect().right}))));assert.equal(overflow,false,'No page overflow at '+width);}
 await page.getByRole('button',{name:'Ny arbetsorder',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Spara',exact:true}).click();await page.getByRole('dialog').getByRole('alert').waitFor();assert(await page.getByRole('dialog').getByRole('alert').textContent().then(t=>t.includes('Ordernummer')&&t.includes('Titel')&&t.includes('Projekt')));await page.getByRole('dialog').getByRole('button',{name:'Avbryt'}).click();
 await page.getByRole('button',{name:'Byt till ljust tema'}).click();assert.equal(await page.locator('html').getAttribute('data-theme'),'light');assert.deepEqual(errors,[]);console.log('PASS: login, theme icons, account menu, colleague registration validation, profile password confirmation, order validation, 320–1440px');
 }finally{await browser.close();server.kill();}
})().catch(e=>{console.error(e);server.kill();process.exitCode=1;});
